packages:
  - "apps/*"
  - "packages/*"
  - "lib"
allowBuilds:
  esbuild: true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: true
  '@firebase/util': true
  protobufjs: true
  core-js: true
onlyBuiltDependencies:
  - esbuild
overrides:
  jose: 4.15.9
