export { importQuestionsFromDocx, parseQuestionText } from './docx-importer';
export type { ImportOptions } from './docx-importer';
export type {
  ImportResult,
  ImportedActivity,
  ActivityType,
  ActivityContent,
  ErrorCode,
  ImportError,
  McqContent,
  McqCategory,
  McqQuestion,
  McqOption,
  DragDropContent,
  ReadingContent,
  ReadingPart,
  ReadingQuestion,
  RewriteContent,
  RewriteQuestion,
  CorrectContent,
  CorrectQuestion,
  DialogueContent,
  DialogueLine,
  TrueFalseContent,
  TrueFalseQuestion,
  WritingContent,
  Severity,
  ValidationIssue,
  ValidationReport,
  UnknownMarkerRecovery,
  WordBankValidation,
  AnswerKeyValidation,
  ReadingValidation,
  McqValidation,
  DialogueValidation,
  DocumentValidation,
  RecoveryAction,
} from './types';
export { validateAll, detectUnknownMarkers, validateAnswerKeys, validateWordBank, validateReading, validateDialogue, validateMcq, validateDocument } from './validation-engine';
export { generateImportReport } from './import-report';
export type { ImportSummary, FormattedReport } from './import-report';
