import { PERMISSIONS, type Permission } from "@el-bannawy/shared";
import {
  Home,
  BookOpen,
  ScrollText,
  BookMarked,
  Users,
  Sparkles,
  GraduationCap,
  BarChart3,
  Settings,
  Gamepad2,
  Trophy,
  Layers,
  Award,
  LifeBuoy,
  RefreshCw,
  UserCog,
  ShoppingCart,
  Coins,
  Key,
  FileCheck,
  Smartphone,
  Shield,
  ClipboardList,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export interface NavModule {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly icon: LucideIcon;
  readonly route: string;
  readonly permission: Permission | null;
  readonly sidebar: boolean;
  readonly dashboard: boolean;
  readonly order: number;
  readonly category: "content" | "management" | "student" | "settings" | null;
}

export const NAV_REGISTRY: readonly NavModule[] = [
  {
    id: "home",
    title: "الرئيسية",
    description: "لوحة التحكم الرئيسية",
    icon: Home,
    route: "/dashboard",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 1,
    category: null,
  },
  {
    id: "units",
    title: "الوحدات التعليمية",
    description: "إنشاء وإدارة الوحدات التعليمية والدروس ومحتوى الدروس",
    icon: BookOpen,
    route: "/dashboard/units",
    permission: PERMISSIONS.UNITS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 10,
    category: "content",
  },
  {
    id: "story",
    title: "قصة المنهج",
    description: "إدارة قصص المنهج والفصول",
    icon: ScrollText,
    route: "/dashboard/stories",
    permission: PERMISSIONS.STORY_VIEW,
    sidebar: true,
    dashboard: true,
    order: 20,
    category: "content",
  },
  {
    id: "final-review",
    title: "المراجعة النهائية",
    description: "إدارة محتوى المراجعة النهائية لكل صف دراسي",
    icon: BookMarked,
    route: "/dashboard/final-reviews",
    permission: PERMISSIONS.FINAL_REVIEW_VIEW,
    sidebar: true,
    dashboard: true,
    order: 30,
    category: "content",
  },
  {
    id: "live",
    title: "الحصص المباشرة",
    description: "إنشاء وإدارة الحصص المباشرة",
    icon: Users,
    route: "/dashboard/live",
    permission: PERMISSIONS.LIVE_VIEW,
    sidebar: true,
    dashboard: true,
    order: 40,
    category: "content",
  },
  {
    id: "teacher-homework",
    title: "الواجبات",
    description: "إدارة ومتابعة واجبات الطلاب",
    icon: ClipboardList,
    route: "/dashboard/teacher/homework",
    permission: PERMISSIONS.HOMEWORK_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 35,
    category: "content",
  },
  {
    id: "teacher-quiz",
    title: "الاختبارات",
    description: "إدارة ومتابعة اختبارات الطلاب",
    icon: GraduationCap,
    route: "/dashboard/teacher/quiz",
    permission: PERMISSIONS.QUIZZES_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 36,
    category: "content",
  },
  {
    id: "educational-systems",
    title: "الأنظمة التعليمية",
    description: "إدارة الأنظمة التعليمية والمراحل والصفوف الدراسية",
    icon: GraduationCap,
    route: "/dashboard/admin/educational-systems",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 55,
    category: "management",
  },
  {
    id: "stages",
    title: "المراحل الدراسية",
    description: "إدارة المراحل الدراسية لكل نظام تعليمي",
    icon: Layers,
    route: "/dashboard/admin/stages",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 56,
    category: "management",
  },
  {
    id: "users",
    title: "المستخدمون",
    description: "إدارة الطلاب والمعلمين",
    icon: Users,
    route: "/dashboard/admin/users",
    permission: PERMISSIONS.USERS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 58,
    category: "management",
  },
  {
    id: "roles",
    title: "الأدوار والصلاحيات",
    description: "عرض الأدوار والصلاحيات في المنصة",
    icon: Shield,
    route: "/dashboard/admin/roles",
    permission: PERMISSIONS.ROLES_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 59,
    category: "management",
  },
  {
    id: "grades",
    title: "الصفوف الدراسية",
    description: "إدارة الصفوف الدراسية لكل مرحلة",
    icon: BookOpen,
    route: "/dashboard/admin/grades",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 57,
    category: "management",
  },
  {
    id: "students",
    title: "الطلاب",
    description: "عرض وإدارة الطلاب المسجلين",
    icon: GraduationCap,
    route: "/dashboard/students",
    permission: PERMISSIONS.STUDENTS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 60,
    category: "management",
  },
  {
    id: "teachers",
    title: "المعلمون",
    description: "إدارة المعلمين والصلاحيات الدراسية",
    icon: UserCog,
    route: "/dashboard/teachers",
    permission: PERMISSIONS.USERS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 65,
    category: "management",
  },
  {
    id: "reports",
    title: "التقارير",
    description: "إنشاء تقارير الأداء والتقدم",
    icon: BarChart3,
    route: "/dashboard/reports",
    permission: PERMISSIONS.REPORTS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 70,
    category: "management",
  },
  {
    id: "admin-setup",
    title: "أدوات الإعداد",
    description: "ترحيل البيانات وإعداد النظام",
    icon: Wrench,
    route: "/dashboard/admin/setup",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 75,
    category: "settings",
  },
  {
    id: "settings",
    title: "الإعدادات",
    description: "تعديل الإعدادات والتفضيلات",
    icon: Settings,
    route: "/dashboard/admin/settings",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 80,
    category: "settings",
  },
  {
    id: "mistakes",
    title: "تعلم من أخطائك",
    description: "راجع الإجابات الخاطئة وحسن مستواك",
    icon: RefreshCw,
    route: "/dashboard/mistakes",
    permission: PERMISSIONS.MISTAKES_VIEW,
    sidebar: true,
    dashboard: true,
    order: 90,
    category: "student",
  },
  {
    id: "games",
    title: "الألعاب التعليمية",
    description: "العب ألعاباً لتحسين المفردات والقواعد والقراءة",
    icon: Gamepad2,
    route: "/dashboard/games",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 100,
    category: "student",
  },
  {
    id: "teacher-games",
    title: "إدارة الألعاب",
    description: "اضبط إعدادات الألعاب التعليمية",
    icon: Gamepad2,
    route: "/dashboard/teacher/games",
    permission: PERMISSIONS.VOCABULARY_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 69,
    category: "management",
  },
  {
    id: "achievements",
    title: "الإنجازات",
    description: "تابع إنجازاتك التعليمية",
    icon: Award,
    route: "/dashboard/achievements",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 110,
    category: "student",
  },
  {
    id: "leaderboard",
    title: "العباقرة",
    description: "قائمة المتصدرين",
    icon: Trophy,
    route: "/dashboard/leaderboard",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 120,
    category: "student",
  },
  {
    id: "competitions",
    title: "المسابقات",
    description: "إدارة المسابقات وتحديات الطلاب",
    icon: Gamepad2,
    route: "/dashboard/competitions",
    permission: PERMISSIONS.COMPETITION_MANAGE,
    sidebar: true,
    dashboard: true,
    order: 63,
    category: "management",
  },
  {
    id: "teacher-leaderboard",
    title: "العباقرة",
    description: "إدارة قائمة العباقرة وترتيب الطلاب",
    icon: Trophy,
    route: "/dashboard/teacher/leaderboard",
    permission: PERMISSIONS.REPORTS_VIEW,
    sidebar: true,
    dashboard: true,
    order: 64,
    category: "management",
  },
  {
    id: "coin-packages",
    title: "باقات العملات",
    description: "إدارة باقات شراء العملات",
    icon: Coins,
    route: "/dashboard/admin/coin-packages",
    permission: PERMISSIONS.COINS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 65,
    category: "management",
  },
  {
    id: "unlock-codes",
    title: "رموز التفعيل",
    description: "إنشاء وإدارة رموز التفعيل",
    icon: Key,
    route: "/dashboard/admin/unlock-codes",
    permission: PERMISSIONS.UNLOCK_CODES_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 66,
    category: "management",
  },
  {
    id: "unlock-requests",
    title: "طلبات فتح المحتوى",
    description: "مراجعة طلبات فتح المحتوى",
    icon: FileCheck,
    route: "/dashboard/admin/unlock-requests",
    permission: PERMISSIONS.UNLOCK_REQUESTS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 67,
    category: "management",
  },
  {
    id: "support-contacts",
    title: "بيانات الدعم الفني",
    description: "إدارة أرقام التواصل للدعم الفني لكل صف",
    icon: Smartphone,
    route: "/dashboard/admin/support-contacts",
    permission: PERMISSIONS.SETTINGS_MANAGE,
    sidebar: true,
    dashboard: false,
    order: 68,
    category: "management",
  },
  {
    id: "support",
    title: "الدعم الفني",
    description: "تواصل مع فريق الدعم",
    icon: LifeBuoy,
    route: "/dashboard/support",
    permission: null,
    sidebar: true,
    dashboard: false,
    order: 130,
    category: "student",
  },
  {
    id: "support-management",
    title: "إدارة الدعم الفني",
    description: "إدارة تذاكر الدعم والرد على الاستفسارات",
    icon: LifeBuoy,
    route: "/dashboard/support",
    permission: PERMISSIONS.SUPPORT_ANSWER,
    sidebar: true,
    dashboard: true,
    order: 71,
    category: "management",
  },
  {
    id: "shop",
    title: "المتجر",
    description: "اشتر العملات وافتح المحتوى",
    icon: ShoppingCart,
    route: "/dashboard/shop",
    permission: PERMISSIONS.COINS_PURCHASE,
    sidebar: true,
    dashboard: true,
    order: 135,
    category: "student",
  },
] as const;

export function getSidebarModules(can: (p: Permission) => boolean): readonly NavModule[] {
  return NAV_REGISTRY.filter(
    (m) => m.sidebar && (m.permission === null || can(m.permission)),
  );
}

export function getDashboardModules(can: (p: Permission) => boolean): readonly NavModule[] {
  return NAV_REGISTRY.filter(
    (m) => m.dashboard && m.permission !== null && can(m.permission),
  );
}
